supject1 = input ("intet the sub you wann do: ")
print ("------------------------------")
supject2 = input ("intet the sub you wann do: ")
print ("------------------------------")
supject3 = input ("intet the sub you wann do: ")
list = [supject1, supject2, supject3]
list.sort()
print ("------------------------------")
print ("you have to do " +str(list))
did_you_done_anything1 = input ("did you done anything? ")
list.remove(did_you_done_anything1)
print ("------------------------------")
print (list)

did_you_done_anything2 = input ("did you done anything? ")
list.remove(did_you_done_anything2)
print ("------------------------------")
print (list)

did_you_done_anything3 = input ("did you done anything? ")
list.remove(did_you_done_anything3)
list.append("congrats! you dona all your tasks")
print ("------------------------------")
print (list)